# Generated by Django 4.1.6 on 2023-03-02 08:39

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "Male"), (1, "Female"), (2, "Trans")]
                    ),
                ),
                (
                    "profile_pic_url",
                    models.URLField(verbose_name="Profile pic location"),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Andhra Pradesh"),
                            (2, "Arunachal Pradesh"),
                            (3, "Assam"),
                            (4, "Bihar"),
                            (5, "Chhattisgarh"),
                            (6, "Goa"),
                            (7, "Gujarat"),
                            (8, "Haryana"),
                            (9, "Himachal Pradesh"),
                            (10, "Jharkhand"),
                            (11, "Karnataka"),
                            (12, "Kerala"),
                            (13, "Madhya Pradesh"),
                            (14, "Maharashtra"),
                            (15, "Manipur"),
                            (16, "Meghalaya"),
                            (17, "Mizoram"),
                            (18, "Nagaland"),
                            (19, "Odisha"),
                            (20, "Punjab"),
                            (21, "Rajasthan"),
                            (22, "Sikkim"),
                            (23, "Tamil Nadu"),
                            (24, "Telangana"),
                            (25, "Tripura"),
                            (26, "Uttar Pradesh"),
                            (27, "Uttarakhand"),
                            (28, "West Bengal"),
                            (29, "Andaman and Nicobar Islands"),
                            (30, "Chandigarh"),
                            (31, "Dadra and Nagar Haveli and Daman and Diu"),
                            (32, "Delhi"),
                            (33, "Jammu and Kashmir"),
                            (34, "Ladakh"),
                            (35, "Lakshadweep"),
                            (36, "Puducherry"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(3, "Hi"), (2, "Md"), (1, "Lo")], default=1
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang_code",
                    core.fields.UpperField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z]+$")
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["name"], name="genre_idx"),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["name"], name="facilities_name_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["name"], name="cities_idx"),
        ),
    ]
