# Generated by Django 4.1.6 on 2023-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="icon_url",
            field=models.URLField(blank=True, null=True, verbose_name="Icon location"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="profile_pic_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Profile pic location"
            ),
        ),
    ]
