# Generated by Django 4.1.6 on 2023-03-10 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingslot",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="uniq_booking_idx",
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("slot_grp", "row", "seat_number")},
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookingslot",
            unique_together={("movie", "screen", "screening_datetime")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["slot_grp", "row", "seat_number"],
                name="uniq_booking_idx",
            ),
        ),
    ]
