# Generated by Django 4.1.6 on 2023-04-17 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_bookingslot_subtitles_lang"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="descriptiom",
            new_name="description",
        ),
    ]
