# Generated by Django 4.1.6 on 2023-04-17 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_slotgroup_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slotgroup",
            name="currency",
        ),
    ]
