# Generated by Django 4.1.6 on 2023-04-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_remove_slotgroup_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingslot",
            name="format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="format_slot",
                to="movies.movieformat",
            ),
        ),
    ]
