# Generated by Django 4.1.6 on 2023-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0002_city_icon_url_alter_artist_profile_pic_url"),
        ("movies", "0009_alter_booking_slot_grp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.ManyToManyField(
                blank=True, related_name="cast_movies", to="meta.artist"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="crew_movies", to="meta.artist"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="subtitles_lang",
            field=models.ManyToManyField(
                blank=True,
                related_name="subtitle_lang_movies",
                to="meta.language",
            ),
        ),
    ]
