# Generated by Django 4.1.6 on 2023-04-20 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0010_alter_movie_cast_alter_movie_crew_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theatre",
            name="details",
        ),
    ]
