# Generated by Django 4.1.6 on 2023-04-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_alter_screen_screen_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingslot",
            name="layout",
        ),
        migrations.AddField(
            model_name="screen",
            name="layout",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
