# Generated by Django 4.1.6 on 2023-04-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_remove_bookingslot_layout_screen_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="screen_id",
            field=models.CharField(max_length=5),
        ),
    ]
