# Generated by Django 4.1.6 on 2023-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_alter_screen_screen_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieformat",
            name="format",
            field=models.CharField(max_length=8),
        ),
    ]
