# Generated by Django 4.1.6 on 2023-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0015_alter_movieformat_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieformat",
            name="format",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
