# Generated by Django 4.1.6 on 2023-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0016_alter_movieformat_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingslot",
            name="current_layout",
            field=models.TextField(blank=True, null=True),
        ),
    ]
