# Generated by Django 4.1.6 on 2023-04-28 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0017_bookingslot_current_layout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="updated_at",
        ),
    ]
