# Generated by Django 4.1.6 on 2023-04-28 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0018_alter_booking_options_remove_booking_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="transaction_id",
        ),
    ]
