# Generated by Django 4.1.6 on 2023-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_remove_booking_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
