# Generated by Django 4.1.6 on 2023-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0020_movie_poster_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="current_layout",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="slotgroup",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
